### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by Yushu2606** [VoryWork/LLandEX#13]
领地数量过多（~250个）导致每次计时器执行时都会造成迟延

**Comment by VoryWork** [comment]
理论上计时器时间复杂度为只和玩家数量有关，可排查是哪条指令引起时延。

**Comment by VoryWork** [comment]
若为索引系统本身问题，只好通过换用引擎解决。

**Comment by VoryWork** [comment]
试一下1.0.18版本，更换了计时器的执行模式

**Comment by Yushu2606** [comment]
> 试一下1.0.18版本，更换了计时器的执行模式

问题依旧，但变得时有时无（不过我用的是去掉一些我用不到的功能的版本）
可能是与监听器有关

**Comment by VoryWork** [comment]
我这边没有大型服务器了所以没办法测试，可以把监听器用二分法排查一下。
