### ISSUE TITLE
与orgex对接后文件占用

### ISSUE THREAD

**Issue by Sujinmu** [VoryWork/LLandEX#14]
13:36:38 ERROR [LevelDB] Fail to load KVDB <./plugins/orgEX/offlineMoney/>
13:36:38 ERROR [LevelDB] IO error: ./plugins/orgEX/offlineMoney//LOCK: 另一个程序正在使用此文件，进程无法访问。
13:36:38 ERROR [LiteLoader] Fail in Loading Script Plugin!

13:36:38 ERROR [LiteLoader] Fail to load ./plugins/O[公会]orgEX.lxl.js!
13:36:38 ERROR [LiteLoader] In Plugin: orgEX
13:36:38 ERROR [LiteLoader] script::Exception can't create class KVDatabase
    at <eval> (./plugins/O[公会]orgEX.lxl.js:104)

**Comment by VoryWork** [comment]
直接删掉``./plugins/orgEX/offlineMoney``
