### ISSUE TITLE
landex领地主人使用铁砧时无法正常附魔

### ISSUE THREAD

**Issue by yumo135** [VoryWork/LLandEX#8]
landex领地主人在使用铁砧时无法正常用附魔书附魔，但会损耗铁砧

![QQ视频_6525b2d5388bd2216522411b08ee47421651934704](https://user-images.githubusercontent.com/88477518/167259596-f5f740fa-60fe-4ae5-9ed9-5d34019daf23.gif)

**Comment by yumo135** [comment]
landex版本v1.0.15，已排除服务器延迟，此处问题是在对非权限玩家禁止铁砧情况下进行

**Comment by VoryWork** [comment]
请按照以下步骤测试：
- [ ] 卸载LLandEX，进行同样操作
- [ ] 若卸载后问题消失，将本代码复制为js插件测试
- [x] 回退旧版本LL与LandEX测试，本人测试2.2.1正常 
```
mc.listen("onUseItemOn",function (player, item, block, side) {
    return;
});
```

**Comment by VoryWork** [comment]
LLAC问题
