### ISSUE TITLE
在其他人的领地上还能挖方块

### ISSUE THREAD

**Issue by nansheng181** [VoryWork/LLandEX#9]
我不知道是什么东西冲突了，但是在其他人领地上能挖方块但是没办法放方块，我啥都没动，不知道怎么回事求大佬解答
然后后台报错了这个：10:19:56 ERROR [LiteLoader] LLandEX - Plugin require load failed

**Comment by nansheng181** [comment]
这是怎么回事

**Comment by VoryWork** [comment]
安装OrgEX
